### Get Technologies
GET localhost:8000/technology

### Get Technology
@id =68bff892d075b39071c1b651
GET localhost:8000/technology/{{id}}

### Post Technology
POST localhost:8000/technology
Content-Type: application/json

{
  "name": "Node.js",
  "category": "Framework",
  "stage": "Test",
  "technologyDescription": "TEEEEESSSTT",
  "classificationDescription": "JavaScript runtime environment"
}
